#!/usr/bin/env python3

# NOTE: this example requires PyAudio because it uses the Microphone class

import serial
import time
import speech_recognition as sr

# connect to the arduino and wait for connection acknowledgement
def connect():
    global arduino
    #Initiate a connection
    arduino = serial.Serial('/dev/ttyACM0', 9600)
    #Read confirmation from Arduino
    while True:
        try:
            time.sleep(0.01)
            #read the message from the Arduino
            raw_message = str(arduino.readline())
            print(raw_message)
            #remove EOL characters from string
            message = raw_message.rstrip()
            if message == "Serial Connected":
                return message
        except:
            pass
            KeyboardInterrupt

connect()
